const BUREAUS = ['TransUnion', 'Experian', 'Equifax'];
const emptyAnalysis = () => ({
  clientProfile: { provider: 'Unknown', clientName: '', reportDate: '' },
  scores: { TransUnion: '', Experian: '', Equifax: '' },
  accountSummary: { totalAccounts: '', openAccounts: '', closedAccounts: '', delinquentAccounts: '', derogatoryAccounts: '', collections: '', balances: '', payments: '', publicRecords: '', inquiries: '' },
  tradelines: [], negativeItems: [], positiveItems: [], bureauDifferences: [], rebuildNeeds: []
});
let rawText = ''; let analysis = emptyAnalysis(); let approved = false;
const clean = (value) => String(value || '').replace(/\s+/g, ' ').replace(/^[|:;,-]+|[|:;,-]+$/g, '').trim();
function detectProvider(text) { if (/identityiq|identity iq/i.test(text)) return 'IdentityIQ'; if (/credit\s*hero/i.test(text)) return 'Credit Hero'; if (/smart\s*credit|smartcredit/i.test(text)) return 'SmartCredit'; return 'Unknown'; }
function findValue(text, labels) { for (const label of labels) { const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); const match = text.match(new RegExp(`${escaped}\\s*[:#-]?\\s*([^\\n\\r|]+)`, 'i')); if (match?.[1]) return clean(match[1]); } return ''; }
function findNumber(text, labels) { const value = findValue(text, labels); const match = String(value).match(/\$?[\d,]+(?:\.\d{2})?/); return match ? match[0] : ''; }
function getSection(text, title, nextTitles = []) { const start = text.search(new RegExp(`(^|\\n)\\s*${title}\\s*($|\\n)`, 'i')); if (start < 0) return ''; const tail = text.slice(start); let end = tail.length; for (const next of nextTitles) { const idx = tail.slice(1).search(new RegExp(`(^|\\n)\\s*${next}\\s*($|\\n)`, 'i')); if (idx >= 0) end = Math.min(end, idx + 1); } return tail.slice(0, end).trim(); }
function parseScores(text) { const scores = { TransUnion: '', Experian: '', Equifax: '' }; BUREAUS.forEach((bureau) => { const short = bureau === 'TransUnion' ? 'TU' : bureau === 'Experian' ? 'EXP' : 'EQF'; const direct = text.match(new RegExp(`${bureau}|${short}`, 'i')); if (direct) { const nearby = text.slice(direct.index, direct.index + 120).match(/\b([3-8]\d{2})\b/); if (nearby) scores[bureau] = nearby[1]; } }); const scoreSection = getSection(text, 'Credit Score', ['Personal Information', 'Account Summary']); if (scoreSection) BUREAUS.forEach((bureau) => { if (!scores[bureau]) scores[bureau] = findNumber(scoreSection, [bureau]); }); return scores; }
function parseTradelines(text) { const accountHistory = getSection(text, 'Account History', ['Inquiries', 'Public Information', 'Creditor Contacts']); const source = accountHistory || text; return source.split(/\n+/).map(clean).filter(Boolean).filter((line) => !/^(account history|credit score|personal information|account summary|inquiries|public information|creditor contacts)$/i.test(line) && !/^(transunion|experian|equifax|creditor|account|balance|payment|status|date|opened|closed)$/i.test(line) && /\b(open|closed|paid|charge.?off|collection|late|current|derogatory|delinquent)\b/i.test(line) && /[A-Za-z]{3,}/.test(line)).map((line, index) => ({ id: index + 1, creditor: clean(line.split(/\s{2,}|\|/)[0]), status: clean((line.match(/\b(open|closed|paid|charge.?off|collection|late|current|derogatory|delinquent)\b/i) || [])[0]), balance: (line.match(/\$[\d,]+(?:\.\d{2})?|\b[\d,]+\.\d{2}\b/) || [])[0] || '', bureaus: BUREAUS.filter((b) => new RegExp(b, 'i').test(line)).join(', '), raw: line })); }
function parseReport(text) { const provider = detectProvider(text); const personal = getSection(text, 'Personal Information', ['Account Summary', 'Account History']); const summary = getSection(text, 'Account Summary', ['Account History', 'Inquiries', 'Public Information']); const inquiries = getSection(text, 'Inquiries', ['Public Information', 'Creditor Contacts']); const publicInfo = getSection(text, 'Public Information', ['Creditor Contacts']); const tradelines = parseTradelines(text); const negativeItems = tradelines.filter((t) => /charge|collection|late|derogatory|delinquent/i.test(`${t.status} ${t.raw}`)); const positiveItems = tradelines.filter((t) => /current|paid|open/i.test(`${t.status} ${t.raw}`) && !negativeItems.includes(t)); return { clientProfile: { provider, clientName: findValue(personal || text, ['Client Name', 'Consumer Name', 'Name']), reportDate: findValue(text, ['Report Date', 'Date Pulled', 'Prepared For Date']) }, scores: parseScores(text), accountSummary: { totalAccounts: findNumber(summary || text, ['Total Accounts', 'Accounts']), openAccounts: findNumber(summary || text, ['Open Accounts', 'Open']), closedAccounts: findNumber(summary || text, ['Closed Accounts', 'Closed']), delinquentAccounts: findNumber(summary || text, ['Delinquent Accounts', 'Delinquent']), derogatoryAccounts: findNumber(summary || text, ['Derogatory Accounts', 'Derogatory']), collections: findNumber(summary || text, ['Collections', 'Collection Accounts']), balances: findNumber(summary || text, ['Balances', 'Total Balance', 'Balance']), payments: findNumber(summary || text, ['Payments', 'Monthly Payments', 'Payment']), publicRecords: findNumber(publicInfo || summary || text, ['Public Records', 'Public Information']), inquiries: findNumber(inquiries || summary || text, ['Inquiries', 'Credit Inquiries']) }, tradelines, negativeItems, positiveItems, bureauDifferences: tradelines.filter((t) => t.bureaus && t.bureaus.split(',').length < 3).map((t) => `${t.creditor}: appears to vary by bureau (${t.bureaus || 'bureau not specified'}).`), rebuildNeeds: [] }; }
function makeStrategy(data) { const blockers = []; if (data.negativeItems.length) blockers.push(`${data.negativeItems.length} negative tradeline(s) require factual verification.`); if (data.accountSummary.collections) blockers.push(`${data.accountSummary.collections} collection item(s) reported in the pasted file.`); if (data.accountSummary.publicRecords) blockers.push(`${data.accountSummary.publicRecords} public record item(s) reported in the pasted file.`); if (!blockers.length) blockers.push('No specific score blockers were verified from the pasted text. Review manually before advising the client.'); const disputes = data.negativeItems.map((item) => `${item.creditor}: verify balance, dates, status, ownership, payment history, and bureau-level reporting.`); return { fileSummary: `${data.clientProfile.clientName || 'Client'} file parsed from ${data.clientProfile.provider}. Scores captured: ${BUREAUS.filter((b) => data.scores[b]).join(', ') || 'none verified'}. Tradelines captured: ${data.tradelines.length}.`, biggestScoreBlockers: blockers, disputePriorities: disputes.length ? disputes : ['No dispute priority can be created until a negative item is verified.'], factualDisputeAngles: ['Verify account ownership.', 'Verify current balance and past-due amount.', 'Verify open/closed status and date fields.', 'Verify payment history and derogatory notation accuracy.'], bureauInconsistencyAngles: data.bureauDifferences.length ? data.bureauDifferences : ['No bureau inconsistency was verified from the pasted text.'], rebuildStrategy: ['Protect every open positive account with on-time payments.', 'Keep revolving utilization low if revolving balances are present.', 'Add positive credit only after verified negatives and utilization risks are understood.'], mortgageReadinessNotes: ['Do not add new debt before lender review.', 'Resolve or document verified collections/public records before pre-approval.', 'Maintain clean 30/60/90-day payment history.'], thirtyDayPlan: ['Complete verification edits.', 'Prioritize verified negative items.', 'Prepare factual dispute letters from verified inaccuracies.'], sixtyDayPlan: ['Review bureau responses.', 'Update utilization and payment status.', 'Escalate unresolved factual inaccuracies.'], ninetyDayPlan: ['Re-pull and compare bureau changes.', 'Confirm score movement and remaining blockers.', 'Prepare lender-readiness checklist if mortgage-bound.'], clientUpdateMessage: 'Your pasted credit report has been reviewed and organized. We will focus first on verified score blockers, bureau inconsistencies, and rebuild steps that support your 30/60/90-day plan.' }; }
const el = (tag, attrs = {}, children = []) => { const node = document.createElement(tag); Object.entries(attrs).forEach(([k, v]) => { if (k === 'class') node.className = v; else if (k === 'text') node.textContent = v; else if (k.startsWith('on')) node.addEventListener(k.slice(2), v); else node.setAttribute(k, v); }); children.forEach((c) => node.append(c)); return node; };
function input(value, oninput, placeholder = '') { const node = el('input', { value, placeholder }); node.addEventListener('input', (e) => oninput(e.target.value)); return node; }
function render() { const root = document.getElementById('root'); root.innerHTML = ''; root.append(el('main', {}, [el('section', { class: 'hero' }, [el('p', { class: 'eyebrow', text: 'Synergy4Life' }), el('h1', { text: 'Credit File Analyzer' }), el('p', { text: 'Paste copied report text, verify extracted fields, then approve a strategic credit game plan. Stage 1 supports pasted text only.' })]), pasteCard(), verificationCard(), strategyCard()])); }
function pasteCard() { const area = el('textarea', { placeholder: 'Paste IdentityIQ, Credit Hero, SmartCredit, or unknown provider report text here...' }); area.value = rawText; area.addEventListener('input', (e) => rawText = e.target.value); const button = el('button', { text: 'Analyze Credit File', onclick: () => { analysis = parseReport(rawText); approved = false; render(); } }); if (!rawText.trim()) button.disabled = true; return el('section', { class: 'card' }, [el('h2', { text: '1. Paste Credit Report Text' }), area, button]); }
function verificationCard() { const grid = el('div', { class: 'grid' }); [['clientProfile', analysis.clientProfile], ['scores', analysis.scores], ['accountSummary', analysis.accountSummary]].forEach(([section, obj]) => Object.entries(obj).forEach(([key, value]) => grid.append(el('label', { text: key }, [input(value, (v) => { analysis[section][key] = v; })])))); return el('section', { class: 'card' }, [el('h2', { text: '2. Manual Verification' }), el('p', { class: 'notice', text: 'Review and edit parsed data. Strategy stays locked until approval.' }), grid, listEditor('Tradelines', 'tradelines'), listEditor('Negative Items', 'negativeItems'), textListEditor('Bureau Differences', 'bureauDifferences'), el('button', { class: 'approve', text: 'Approve Credit File Analysis', onclick: () => { approved = true; render(); } })]); }
function listEditor(title, key) { const box = el('div', { class: 'subcard' }, [el('h3', { text: title })]); if (!analysis[key].length) box.append(el('p', { class: 'muted', text: `No verified ${title.toLowerCase()} parsed.` })); analysis[key].forEach((row, i) => box.append(el('div', { class: 'row' }, [input(row.creditor || '', (v) => analysis[key][i].creditor = v, 'creditor'), input(row.status || '', (v) => analysis[key][i].status = v, 'status'), input(row.balance || '', (v) => analysis[key][i].balance = v, 'balance')]))); return box; }
function textListEditor(title, key) { const box = el('div', { class: 'subcard' }, [el('h3', { text: title })]); if (!analysis[key].length) box.append(el('p', { class: 'muted', text: `No verified ${title.toLowerCase()} parsed.` })); analysis[key].forEach((row, i) => box.append(input(row, (v) => analysis[key][i] = v))); return box; }
function strategyCard() { const box = el('section', { class: `card ${approved ? '' : 'locked'}` }, [el('h2', { text: '3. Strategy & 30/60/90 Game Plan' })]); if (!approved) box.append(el('p', { class: 'notice', text: 'Approve the verified credit file analysis to generate strategy.' })); else { const strategy = makeStrategy(analysis); box.append(el('p', { text: strategy.fileSummary })); Object.entries(strategy).filter(([k]) => k !== 'fileSummary').forEach(([k, v]) => { const part = el('div', {}, [el('h3', { text: k.replace(/[A-Z]/g, ' $&') })]); if (Array.isArray(v)) part.append(el('ul', {}, v.map((x) => el('li', { text: x })))); else part.append(el('p', { text: v })); box.append(part); }); } return box; }
render();
